-- ============================================================
-- 권한관리(RBAC) 물리 모델 - MariaDB DB/테이블 생성 스크립트
--
-- DB명       : mdtest
-- 접속 계정  : mdtest
-- 접속 암호  : mdtest1!
--
-- 테이블/컬럼 COMMENT는 "webdev_erd_2.md ## 4. 테이블 정의"의 설명을 반영했다.
--
-- [실행 방법]
-- 1) DB/계정까지 처음부터 생성할 때 (root 권한 필요)
--      mysql -u root -p < create_mdtest.sql
--    (root 비밀번호 입력 프롬프트가 뜨면 root 계정 비밀번호를 입력)
--
-- 2) DB/계정은 이미 만들어져 있고 테이블만 다시 만들 때
--      mysql -u mdtest -p mdtest < create_mdtest.sql
--    (이 경우 위쪽 CREATE DATABASE/CREATE USER/GRANT 구문은 무시되어도 무방)
-- ============================================================

-- 0. 클라이언트 접속 문자셋을 명시적으로 고정 (한글 COMMENT 깨짐 방지)
--    mysql 클라이언트의 기본 접속 문자셋이 utf8mb4가 아니면(예: Windows 콘솔의
--    latin1/cp949 기본값) 아래 CREATE TABLE의 한글 COMMENT가 깨진 채로 저장된다.
SET NAMES utf8mb4;

-- 1. 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS mdtest
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

-- 2. 접속 계정 생성 및 권한 부여 (mdtest / mdtest1!)
CREATE USER IF NOT EXISTS 'mdtest'@'%' IDENTIFIED BY 'mdtest1!';
CREATE USER IF NOT EXISTS 'mdtest'@'localhost' IDENTIFIED BY 'mdtest1!';

GRANT ALL PRIVILEGES ON mdtest.* TO 'mdtest'@'%';
GRANT ALL PRIVILEGES ON mdtest.* TO 'mdtest'@'localhost';
FLUSH PRIVILEGES;

USE mdtest;

-- 3. 기존 테이블 정리 (재실행 대비, 자식 -> 부모 순서)
DROP TABLE IF EXISTS TB_MY_MENU;
DROP TABLE IF EXISTS TB_USER_PROGRAM;
DROP TABLE IF EXISTS TB_ROLE_PROGRAM;
DROP TABLE IF EXISTS TB_USER_ROLE;
DROP TABLE IF EXISTS TB_PROGRAM;
DROP TABLE IF EXISTS TB_ROLE;
DROP TABLE IF EXISTS TB_USER;
DROP TABLE IF EXISTS TB_CODE;
DROP TABLE IF EXISTS TB_CODE_GROUP;

-- 4. 테이블 생성 (부모 -> 자식 순서)

-- 4.1 TB_USER (사용자)
CREATE TABLE TB_USER (
  USER_ID       VARCHAR(20)  NOT NULL COMMENT '사용자 ID',
  USER_NM       VARCHAR(50)  NOT NULL COMMENT '사용자명',
  DEPT_CD       VARCHAR(10)  NULL     COMMENT '부서 코드',
  USER_STAT_CD  CHAR(1)      NOT NULL COMMENT '사용자 상태 (재직/퇴직 등)',
  REG_DTTM      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID   VARCHAR(20)  NULL     COMMENT '등록자 ID',
  MOD_DTTM      DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID   VARCHAR(20)  NULL     COMMENT '수정자 ID',
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자';

-- 4.2 TB_ROLE (역할)
CREATE TABLE TB_ROLE (
  ROLE_ID     VARCHAR(20)  NOT NULL COMMENT '역할 ID',
  ROLE_NM     VARCHAR(50)  NOT NULL COMMENT '역할명 (예: 시스템관리자, 일반사용자)',
  ROLE_DESC   VARCHAR(200) NULL     COMMENT '역할 설명',
  USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '사용여부 (Y/N)',
  REG_DTTM    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20)  NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20)  NULL     COMMENT '수정자 ID',
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='역할';

-- 4.3 TB_USER_ROLE (사용자-역할 매핑)
CREATE TABLE TB_USER_ROLE (
  USER_ID     VARCHAR(20) NOT NULL COMMENT '사용자 ID',
  ROLE_ID     VARCHAR(20) NOT NULL COMMENT '역할 ID',
  REG_DTTM    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20) NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20) NULL     COMMENT '수정자 ID',
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
  CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자-역할 매핑 (사용자 1명이 여러 역할을 가질 수 있는 N:M 관계)';

-- 4.4 TB_PROGRAM (프로그램/메뉴)
CREATE TABLE TB_PROGRAM (
  PROGRAM_ID        VARCHAR(20)  NOT NULL COMMENT '프로그램(메뉴) ID',
  PARENT_PROGRAM_ID VARCHAR(20)  NULL     COMMENT '상위 메뉴 ID (대메뉴-소메뉴 계층 표현)',
  PROGRAM_NM        VARCHAR(100) NOT NULL COMMENT '메뉴명',
  URL_PATH          VARCHAR(200) NULL     COMMENT '연결 URL/라우팅 경로',
  MENU_ORD          INT          NULL     COMMENT '메뉴 정렬 순서',
  MENU_LVL          TINYINT      NULL     COMMENT '메뉴 depth (1: 대메뉴, 2: 소메뉴 …)',
  USE_YN            CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '메뉴 사용여부 (Y/N)',
  REG_DTTM          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID       VARCHAR(20)  NULL     COMMENT '등록자 ID',
  MOD_DTTM          DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID       VARCHAR(20)  NULL     COMMENT '수정자 ID',
  PRIMARY KEY (PROGRAM_ID),
  CONSTRAINT FK_PROGRAM_PARENT FOREIGN KEY (PARENT_PROGRAM_ID) REFERENCES TB_PROGRAM (PROGRAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='프로그램/메뉴';

-- 4.5 TB_ROLE_PROGRAM (역할별 프로그램 권한)
CREATE TABLE TB_ROLE_PROGRAM (
  ROLE_ID     VARCHAR(20) NOT NULL COMMENT '역할 ID',
  PROGRAM_ID  VARCHAR(20) NOT NULL COMMENT '프로그램 ID',
  VIEW_YN     CHAR(1)     NOT NULL DEFAULT 'N' COMMENT '조회 권한 여부',
  WRITE_YN    CHAR(1)     NOT NULL DEFAULT 'N' COMMENT '등록/수정 권한 여부',
  DELETE_YN   CHAR(1)     NOT NULL DEFAULT 'N' COMMENT '삭제 권한 여부',
  REG_DTTM    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20) NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20) NULL     COMMENT '수정자 ID',
  PRIMARY KEY (ROLE_ID, PROGRAM_ID),
  CONSTRAINT FK_ROLE_PROGRAM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ROLE_ID),
  CONSTRAINT FK_ROLE_PROGRAM_PROGRAM FOREIGN KEY (PROGRAM_ID) REFERENCES TB_PROGRAM (PROGRAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='역할별 프로그램 권한 (로그인 시 메뉴 렌더링의 기본 소스)';

-- 4.6 TB_USER_PROGRAM (사용자별 프로그램 예외 권한)
CREATE TABLE TB_USER_PROGRAM (
  USER_ID     VARCHAR(20) NOT NULL COMMENT '사용자 ID',
  PROGRAM_ID  VARCHAR(20) NOT NULL COMMENT '프로그램 ID',
  ALLOW_YN    CHAR(1)     NOT NULL COMMENT '허용(Y) / 차단(N) 구분',
  VIEW_YN     CHAR(1)     NULL     COMMENT '조회 권한 여부',
  WRITE_YN    CHAR(1)     NULL     COMMENT '등록/수정 권한 여부',
  REG_DTTM    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20) NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20) NULL     COMMENT '수정자 ID',
  PRIMARY KEY (USER_ID, PROGRAM_ID),
  CONSTRAINT FK_USER_PROGRAM_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
  CONSTRAINT FK_USER_PROGRAM_PROGRAM FOREIGN KEY (PROGRAM_ID) REFERENCES TB_PROGRAM (PROGRAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자별 프로그램 예외 권한 (allow_flag가 N이면 역할 권한상 접근 가능해도 해당 사용자는 접근 차단)';

-- 4.7 TB_CODE_GROUP (공통코드 그룹)
CREATE TABLE TB_CODE_GROUP (
  GROUP_CD    VARCHAR(30)  NOT NULL COMMENT '코드 그룹 ID',
  GROUP_NM    VARCHAR(100) NOT NULL COMMENT '코드 그룹명',
  GROUP_DESC  VARCHAR(200) NULL     COMMENT '코드 그룹 설명',
  USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '그룹 사용여부 (Y/N)',
  REG_DTTM    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20)  NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20)  NULL     COMMENT '수정자 ID',
  PRIMARY KEY (GROUP_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통코드 그룹';

-- 4.8 TB_CODE (공통코드 상세)
CREATE TABLE TB_CODE (
  GROUP_CD    VARCHAR(30)  NOT NULL COMMENT '코드 그룹 ID',
  CODE        VARCHAR(30)  NOT NULL COMMENT '코드값',
  CODE_NM     VARCHAR(100) NOT NULL COMMENT '코드명 (화면 표시용)',
  CODE_DESC   VARCHAR(200) NULL     COMMENT '코드 설명',
  SORT_ORD    INT          NULL     COMMENT '정렬 순서',
  USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT '코드 사용여부 (Y/N)',
  REG_DTTM    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20)  NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME     NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20)  NULL     COMMENT '수정자 ID',
  PRIMARY KEY (GROUP_CD, CODE),
  CONSTRAINT FK_CODE_GROUP FOREIGN KEY (GROUP_CD) REFERENCES TB_CODE_GROUP (GROUP_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통코드 상세';

-- 4.9 TB_MY_MENU (나의메뉴)
CREATE TABLE TB_MY_MENU (
  USER_ID     VARCHAR(20) NOT NULL COMMENT '사용자 ID',
  PROGRAM_ID  VARCHAR(20) NOT NULL COMMENT '프로그램 ID',
  SORT_ORD    INT         NULL     COMMENT '나의메뉴 내 표시 순서',
  REG_DTTM    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  REG_USER_ID VARCHAR(20) NULL     COMMENT '등록자 ID',
  MOD_DTTM    DATETIME    NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  MOD_USER_ID VARCHAR(20) NULL     COMMENT '수정자 ID',
  PRIMARY KEY (USER_ID, PROGRAM_ID),
  CONSTRAINT FK_MY_MENU_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
  CONSTRAINT FK_MY_MENU_PROGRAM FOREIGN KEY (PROGRAM_ID) REFERENCES TB_PROGRAM (PROGRAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='나의메뉴 (사용자가 즐겨찾기로 등록한 프로그램)';

-- 5. 공통코드 초기 데이터
-- 대상 컬럼: TB_USER.USER_STAT_CD, TB_PROGRAM.MENU_LVL,
--           TB_ROLE.USE_YN / TB_PROGRAM.USE_YN / TB_ROLE_PROGRAM.VIEW_YN,WRITE_YN,DELETE_YN / TB_USER_PROGRAM.ALLOW_YN,VIEW_YN,WRITE_YN
INSERT INTO TB_CODE_GROUP (GROUP_CD, GROUP_NM, GROUP_DESC) VALUES
('USER_STAT', '사용자 상태', 'TB_USER.USER_STAT_CD 값 목록'),
('MENU_LVL',  '메뉴 레벨',   'TB_PROGRAM.MENU_LVL 값 목록 (메뉴 depth)'),
('YN',        '사용여부(Y/N)', '*_YN 컬럼 공통 목록 (USE_YN/VIEW_YN/WRITE_YN/DELETE_YN/ALLOW_YN 등)');

INSERT INTO TB_CODE (GROUP_CD, CODE, CODE_NM, SORT_ORD) VALUES
('USER_STAT', '1', '재직', 1),
('USER_STAT', '2', '휴직', 2),
('USER_STAT', '3', '퇴직', 3),
('MENU_LVL',  '1', '대메뉴', 1),
('MENU_LVL',  '2', '소메뉴', 2),
('MENU_LVL',  '3', '세부메뉴', 3),
('YN',        'Y', '사용', 1),
('YN',        'N', '미사용', 2);

-- 6. 초기 업무 데이터 (역할/사용자/메뉴)

-- 6.1 TB_ROLE : 역할
INSERT INTO TB_ROLE (ROLE_ID, ROLE_NM, ROLE_DESC, REG_USER_ID) VALUES
('SYSADMIN', '시스템관리자', '시스템 전체 관리 권한을 가진 최고 관리자 역할', 'SYSTEM'),
('GENERAL',  '일반사용자',   '기본 업무 화면 접근 권한을 가진 일반 사용자 역할', 'SYSTEM');

-- 6.2 TB_USER : 사용자
INSERT INTO TB_USER (USER_ID, USER_NM, USER_STAT_CD, REG_USER_ID) VALUES
('admin', '관리자',    '1', 'SYSTEM'),
('wms',   'WMS 사용자', '1', 'SYSTEM');

-- 6.3 TB_USER_ROLE : 사용자-역할 매핑 (admin -> 시스템관리자, wms -> 일반사용자)
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID, REG_USER_ID) VALUES
('admin', 'SYSADMIN', 'SYSTEM'),
('wms',   'GENERAL',  'SYSTEM');

-- 6.4 TB_PROGRAM : 대메뉴(1) - 소메뉴(2) - 프로그램(3)
-- 6.4.1 대메뉴 (MENU_LVL = 1)
INSERT INTO TB_PROGRAM (PROGRAM_ID, PARENT_PROGRAM_ID, PROGRAM_NM, URL_PATH, MENU_ORD, MENU_LVL, REG_USER_ID) VALUES
('AMS', NULL, 'AMS', '/ams', 1, 1, 'SYSTEM'),
('WMS', NULL, 'WMS', '/wms', 2, 1, 'SYSTEM');

-- 6.4.2 소메뉴 (MENU_LVL = 2)
INSERT INTO TB_PROGRAM (PROGRAM_ID, PARENT_PROGRAM_ID, PROGRAM_NM, URL_PATH, MENU_ORD, MENU_LVL, REG_USER_ID) VALUES
('AMS_AUTH',  'AMS', '권한관리', '/ams/auth',  1, 2, 'SYSTEM'),
('WMS_BASE',  'WMS', '기본',     '/wms/base',  1, 2, 'SYSTEM'),
('WMS_IN',    'WMS', '입고',     '/wms/in',    2, 2, 'SYSTEM'),
('WMS_OUT',   'WMS', '출고',     '/wms/out',   3, 2, 'SYSTEM'),
('WMS_STOCK', 'WMS', '재고',     '/wms/stock', 4, 2, 'SYSTEM');

-- 6.4.3 프로그램 (MENU_LVL = 3, 권한관리 하위)
INSERT INTO TB_PROGRAM (PROGRAM_ID, PARENT_PROGRAM_ID, PROGRAM_NM, URL_PATH, MENU_ORD, MENU_LVL, REG_USER_ID) VALUES
('AMS_AUTH_USER',      'AMS_AUTH', '사용자 관리',        '/ams/auth/user',          1, 3, 'SYSTEM'),
('AMS_AUTH_PROG',      'AMS_AUTH', '프로그램 관리',      '/ams/auth/program',       2, 3, 'SYSTEM'),
('AMS_AUTH_ROLE',      'AMS_AUTH', '역할 관리',          '/ams/auth/role',          3, 3, 'SYSTEM'),
('AMS_AUTH_USR_ROLE',  'AMS_AUTH', '사용자별 역할 관리', '/ams/auth/user-role',     4, 3, 'SYSTEM'),
('AMS_AUTH_ROLE_PROG', 'AMS_AUTH', '역할별 프로그램 권한','/ams/auth/role-program', 5, 3, 'SYSTEM'),
('AMS_AUTH_CODE',      'AMS_AUTH', '공통코드',           '/ams/auth/code',          6, 3, 'SYSTEM');

-- 6.5 TB_ROLE_PROGRAM : SYSADMIN에게 AMS_AUTH(권한관리) 하위 프로그램 권한 부여
INSERT INTO TB_ROLE_PROGRAM (ROLE_ID, PROGRAM_ID, VIEW_YN, WRITE_YN, DELETE_YN, REG_USER_ID)
SELECT 'SYSADMIN', PROGRAM_ID, 'Y', 'Y', 'Y', 'SYSTEM'
FROM TB_PROGRAM
WHERE PARENT_PROGRAM_ID = 'AMS_AUTH';

-- 6.6 TB_ROLE_PROGRAM : SYSADMIN에게 나머지 상위 메뉴(AMS, WMS 대메뉴/소메뉴) 전체 권한 부여
-- (6.5에서 이미 등록한 AMS_AUTH 하위 6건을 제외한 나머지 전체 프로그램)
INSERT INTO TB_ROLE_PROGRAM (ROLE_ID, PROGRAM_ID, VIEW_YN, WRITE_YN, DELETE_YN, REG_USER_ID)
SELECT 'SYSADMIN', PROGRAM_ID, 'Y', 'Y', 'Y', 'SYSTEM'
FROM TB_PROGRAM p
WHERE NOT EXISTS (
  SELECT 1 FROM TB_ROLE_PROGRAM rp WHERE rp.ROLE_ID = 'SYSADMIN' AND rp.PROGRAM_ID = p.PROGRAM_ID
);

-- 7. 생성 확인
SHOW TABLES;
